global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Microservices (containerized)
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8090']
    scrape_interval: 5s

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8090']
    scrape_interval: 5s

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8090']
    scrape_interval: 5s

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8090']
    scrape_interval: 5s

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8090']
    scrape_interval: 5s

  - job_name: 'bff-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bff-service:8090']
    scrape_interval: 5s


  # Infrastructure services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Node Exporter (if added later)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

